### ISSUE TITLE
Update CI/CD in readme/example to utilize the ow-cli

### ISSUE THREAD

**Issue by OdedItkinOW** [AlbericoD/overwolf-modern-react-boilerplate#176]
**Is your feature request related to a problem? Please describe.**
Not as much a problem, more a "notification" that the [section about ci/cd](https://github.com/AlbericoD/overwolf-modern-react-boilerplate/blob/master/template/README.md#--%EF%B8%8F-cicd---experimental) in the readme can now probably be updated to support the [ow-cli](https://www.npmjs.com/package/@overwolf/ow-cli) tool 🥳 

**Describe the solution you'd like**
Ideally some sort of mention of the cli tool. Not sure about what the exact phrasing should be to make it fit, but I'll gladly help with phrasing/editing it if you wish.

(Removed the rest of the template as it was slightly N/A)

Feel free to reach out if you do want to update it, and/or if you do require some help with any of it, and thank you once again for maintaining this project!

**Comment by AlbericoD** [comment]
Hi, thanks for the information!
I had forgotten about this, but I'm glad you remembered, I had a quick look and I believe it would be something like this:

I think it would be after line 50 and before the step **"create-github-release"**

```yml
  publish-on-overwolf-store:
    name: Publish on Overwolf Store
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 🛠️ Install ow cli
        run: |
            npm i -g @overwolf/ow-cli
      - name:  config ow cli
        run: |
            ow config --user ${{secrets.OVERWOLF_CI_USER}} --token ${{secrets.OVERWOLF_CI_TOKEN}}
      - name:  prepare app files
        run: |
            ow opk sign dist-opk.v${{fromJson(steps.read_current_version.outputs.packageJson).version}}.opk
      - name:  upload opk to the dev console
        run: |
            ow opk upload dist-opk.v${{fromJson(steps.read_current_version.outputs.packageJson).version}}.opk --wait
      - name:  release opk
        run: |
            ow opk release dist-opk.v${{fromJson(steps.read_current_version.outputs.packageJson).version}}.opk --wait -p 25  //or ${{secrets.OVERWOLF_RELEASE_PERCENT}}
            
 create-github-release:
 ...
```

at the moment I am a little busy but I have some plans to update this repository, some devs approach me on slack and discord suggesting improvements if you want to feel free to improve the CI
